# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
  desktop-file-utils,
  makeWrapper,
  p11-kit,
  polkit,
  tpm2-openssl,
  tpm2-tss,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1gybr6pjvgh3yzf7g2pnd4fzmpndvl1c6p0k5fc2s0r4z4xzlqzg";
    aarch64-linux = "0lg08j3zwn70xv1q5aypwvjvkhz5hkzyxfs9kp00x077fyzaxb47";
  };

  urlMap = {
    x86_64-linux = "https://github.com/smallstep/step-agent-plugin/releases/download/v0.65.0-rc18/step-agent_0.65.0-rc18_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/smallstep/step-agent-plugin/releases/download/v0.65.0-rc18/step-agent_0.65.0-rc18_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "step-agent-plugin";
  version = "0.65.0-rc18";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./step-agent $out/bin/step-agent
    wrapProgram $out/bin/step-agent --prefix PATH : ${lib.makeBinPath (lib.optionals stdenvNoCC.isLinux [ tpm2-tss tpm2-openssl desktop-file-utils polkit p11-kit ])}
  '';

  meta = {
    description = "step-agent-plugin is an automated certificate management agent plugin for step-cli.";
    homepage = "https://github.com/smallstep/step-agent-plugin/";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
