# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
  desktop-file-utils,
  makeWrapper,
  p11-kit,
  polkit,
  tpm2-openssl,
  tpm2-tss,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1qinb6rmvp3cnlsf8zinrddjjk8djh4fnkf24jbj49r590bxpbmd";
    aarch64-linux = "1libq2gdi73l6ncfg0r3w1qk4j3vcrzhi7wrp11l9k7h99zp2iy4";
  };

  urlMap = {
    x86_64-linux = "https://packages.smallstep.com/edge/step-agent/linux/0.69.1-rc3/step-agent_0.69.1-rc3_linux_amd64.tar.gz";
    aarch64-linux = "https://packages.smallstep.com/edge/step-agent/linux/0.69.1-rc3/step-agent_0.69.1-rc3_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "step-agent";
  version = "0.69.1-rc3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./step-agent $out/bin/step-agent
    wrapProgram $out/bin/step-agent --prefix PATH : ${lib.makeBinPath (lib.optionals stdenvNoCC.isLinux [ tpm2-tss tpm2-openssl desktop-file-utils polkit p11-kit ])}
  '';

  meta = {
    description = "step-agent is an automated certificate management agent from Smallstep.";
    homepage = "https://github.com/smallstep/step-agent/";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
