# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
  desktop-file-utils,
  makeWrapper,
  p11-kit,
  polkit,
  tpm2-openssl,
  tpm2-tss,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0g8ylz94bnjmhiqa1c7sgaqpq242f9gkkdg3c436apzdzi7zv8ly";
    aarch64-linux = "1vwl7f8cpfwm9rrg8ji9mzr7zpgvwdddh6y0izky60b8b0l11mg4";
  };

  urlMap = {
    x86_64-linux = "https://packages.smallstep.com/edge/step-agent/linux/0.69.3-rc2/step-agent_0.69.3-rc2_linux_amd64.tar.gz";
    aarch64-linux = "https://packages.smallstep.com/edge/step-agent/linux/0.69.3-rc2/step-agent_0.69.3-rc2_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "step-agent";
  version = "0.69.3-rc2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./step-agent $out/bin/step-agent
    wrapProgram $out/bin/step-agent --prefix PATH : ${lib.makeBinPath (lib.optionals stdenvNoCC.isLinux [ tpm2-tss tpm2-openssl desktop-file-utils polkit p11-kit ])}
  '';

  meta = {
    description = "step-agent is an automated certificate management agent from Smallstep.";
    homepage = "https://github.com/smallstep/step-agent/";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
