# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  tpm2-tss,
  tpm2-openssl,
  desktop-file-utils,
  polkit,
  p11-kit,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0y7q64sg685ipnrzrrylsnyssfk2h1qdp3idqwdxxj8hqpmqqjld";
    aarch64-linux = "0jknk8zcpk5av2wgw9qiycsx83fr88wjhn3yrzn5zr02kmi9izhr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/smallstep/step-agent-plugin/releases/download/v0.64.0-rc1/step-agent-plugin_linux_0.64.0-rc1_amd64.tar.gz";
    aarch64-linux = "https://github.com/smallstep/step-agent-plugin/releases/download/v0.64.0-rc1/step-agent-plugin_linux_0.64.0-rc1_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "step-agent-plugin";
  version = "0.64.0-rc1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = "step-agent-plugin_0.64.0-rc1";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./step-agent-plugin $out/bin/step-agent-plugin
    wrapProgram $out/bin/step-agent-plugin --prefix PATH : ${lib.makeBinPath (lib.optionals stdenvNoCC.isLinux [ tpm2-tss tpm2-openssl desktop-file-utils polkit p11-kit ])}
  '';

  meta = {
    description = "step-agent-plugin is an automated certificate management agent plugin for step-cli.";
    homepage = "https://github.com/smallstep/step-agent-plugin/";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
