# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  tpm2-tss,
  tpm2-openssl,
  desktop-file-utils,
  polkit,
  p11-kit,
  gdk-pixbuf,
  glib,
  gtk3,
  libsoup_3,
  webkitgtk_4_1,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0ji662ddpy980cz6hy9a7z2srbpfappj774ffjqdhl7njq2393j2";
    aarch64-linux = "1x3sa5g1lsr7jlf5dv04jvygy4wzybld7yyj4l6319gkvsjwprrw";
  };

  urlMap = {
    x86_64-linux = "https://github.com/smallstep/step-agent-plugin/releases/download/v0.64.0-rc3/step-agent-plugin_linux_0.64.0-rc3_amd64.tar.gz";
    aarch64-linux = "https://github.com/smallstep/step-agent-plugin/releases/download/v0.64.0-rc3/step-agent-plugin_linux_0.64.0-rc3_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "step-agent-plugin";
  version = "0.64.0-rc3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = "step-agent-plugin_0.64.0-rc3";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./step-agent-plugin $out/bin/step-agent-plugin
    wrapProgram $out/bin/step-agent-plugin --prefix PATH : ${lib.makeBinPath (lib.optionals stdenvNoCC.isLinux [ tpm2-tss tpm2-openssl desktop-file-utils polkit p11-kit gdk-pixbuf glib gtk3 libsoup_3 webkitgtk_4_1 ])}
  '';

  meta = {
    description = "step-agent-plugin is an automated certificate management agent plugin for step-cli.";
    homepage = "https://github.com/smallstep/step-agent-plugin/";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
