name: "Test commit push"
on:
  workflow_dispatch:

jobs:
  test-commit-push:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup bot SSH signing key
      uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
      env:
        HAS_SSH_PRIVATE_KEY: ${{ secrets.STEP_TRAVIS_CI_GH_PRIVATE_SIGNING_KEY != '' }}
      if: ${{ env.HAS_SSH_PRIVATE_KEY == 'true' }}
      with:
        ssh-private-key: |
          ${{ secrets.STEP_TRAVIS_CI_GH_PRIVATE_SIGNING_KEY }}

    - name: Sign commit
      run: |
        git config user.email "eng+ci@smallstep.com"
        git config user.name "step-ci"
        git config --global commit.gpgsign true
        git config --global gpg.format ssh
        git config --global user.signingkey "${{ secrets.STEP_TRAVIS_CI_GH_PUBLIC_SIGNING_KEY }}"
        git commit --allow-empty -m "Test: empty commit from CI"

    - name: Push changes
      uses: ad-m/github-push-action@4cc74773234f74829a8c21bc4d69dd4be9cfa599 # v1.1.0
      with:
        github_token: ${{ secrets.PAT }}
        branch: 'main'
